# Use Ubuntu 14.04
sudo: required
dist: trusty

# Set the language
language: cpp

# Set the compiler
compiler:
    - gcc

# Send e-mails if the build fail
notification:
    email:
        on_success: change
        on_failure: always

# Install pcv dependencies
addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - cmake
            - sqlite3
            - valgrind
            # Without Boost, ParasiteTool is not compilable
            #- libboost-all-dev
            # Google test headers (they need to be compiled)
            - libgtest-dev
            # Install GCC 6 to support C++14 from the above repository
            - gcc-6
            - g++-6

before_install:
    - pip install --user cpp-coveralls


install:
    - cd ${TRAVIS_BUILD_DIR} && pwd
    # install latest LCOV (1.9 was failing for me) [1]
    - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
    - tar xf lcov_1.11.orig.tar.gz
    - sudo make -C lcov-1.11/ install
    # install lcov to coveralls conversion + upload tool
    - gem install coveralls-lcov


before_script:
    - cd ${TRAVIS_BUILD_DIR} && pwd
    # Compile Google Test
    - ./travisCI/gtest_compile.sh
    # Manually download the database (otherwise, Git LFS needs to be installed)
    - wget https://github.com/wilhelma/pcvInterpreter/raw/development/test/databases/integration_test.db -O test/databases/integration_test.db
    - lcov --directory . --zerocounters

# Build
script:
    - cd ${TRAVIS_BUILD_DIR} && pwd
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6 --coverage" CC="gcc-6 --coverage"; fi
    - mkdir build && cd build
    - cmake .. && make -j
    - valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all ./src/pcv ../test/databases/integration_test.db
    - make pcv_test -j && ./test/pcv_test

after_success:
    - cd ${TRAVIS_BUILD_DIR} && pwd
    - lcov --directory . --capture --output-file coverage.info # capture coverage info
    - lcov --remove coverage.info 'easyloggingpp-prefix/*' 'test/*' '/usr/*' 'external/*' 'travisCI/*' --output-file coverage.info # filter out system and test code
    - lcov --list coverage.info # debug before upload
    - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls
