# Use Ubuntu 14.04
sudo: required
dist: trusty

# Set the language
language: cpp

# Set the compiler
compiler:
    - gcc

# Install pcv dependencies
addons:
    apt:
        sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages:
            - cmake
            - sqlite3
            # Without Boost, ParasiteTool is not compilable
            #- libboost-all-dev
            # Google test headers (they need to be compiled)
            - libgtest-dev
            # Install GCC 6 to support C++14 from the above repository
            - gcc-6
            - g++-6

# Sent e-mails if the build fail
notification:
    email:
        on_success: change
        on_failure: always

# Build
script:
    # Manually download the database (otherwise, Git LFS needs to be installed)
    - wget https://github.com/wilhelma/pcvInterpreter/raw/development/test/databases/integration_test.db -O test/databases/integration_test.db
      ## Compile Google Test
    # Compile Google Test
    - ./travisCI/gtest_compile.sh
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - mkdir build && cd build
    - cmake .. && make -j && ./src/pcv ../test/databases/integration_test.db
    - make pcv_test -j && ./test/pcv_test
